pipeline {
    // Run on an agent where we want to use Go
    agent any

    environment {
        APP_NAME = 'collect-admin-api'
        REGISTRY = '192.168.0.102:5000'
        IMAGE_TAG = UUID.randomUUID().toString()
        PORT = '8879'
        ENV = "develop"
    }

    // Ensure the desired Go version is installed for all stages,
    // using the name defined in the Global Tool Configuration
    tools { go 'go1.25.4' }

    stages {
        stage('Build') {
            steps {
                sh 'echo "开始构建..."'
                sh 'go env -w GOPROXY=https://goproxy.cn,direct'
                sh 'go build -o bin/collect-admin-api main.go'
                sh 'chmod +x bin/collect-admin-api'
                sh 'cp -rf resource bin/resource'
                sh 'echo "构建完成"'
                sh 'ls -la bin'
            }
        }
        stage('Build and Push') {
            steps {
                script {
                    // 构建并推送镜像
                    docker.build("${REGISTRY}/${APP_NAME}-${ENV}:${IMAGE_TAG}", "bin").push()
                }
            }
        }
        stage('Deploy to K8s') {
            steps {
                withKubeConfig([
                    credentialsId: 'k8s-kubeconfig',
                    serverUrl: 'http://192.168.0.102:8001'
                ]) {
                    sh '''
                        # 替换变量并应用
                        envsubst < k8s/api/deployment.yaml | kubectl apply -f - --force
                        echo "✅ 部署完成"
                        echo "应用名称: ${APP_NAME}"
                        echo "应用端口: ${PORT}"
                        echo "镜像: ${REGISTRY}/${APP_NAME}-${ENV}:${IMAGE_TAG}"
                    '''
                }
            }
        }
    }
}
