// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/collect/dao/internal"
)

// appsDao is the data access object for the table ct_apps.
// You can define custom methods on it to extend its functionality as needed.
type appsDao struct {
	*internal.AppsDao
}

var (
	// Apps is a globally accessible object for table ct_apps operations.
	Apps = appsDao{internal.NewAppsDao()}
)

// Add your custom methods and functionality below.
