// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/collect/dao/internal"
)

// dispatchDao is the data access object for the table ct_dispatch.
// You can define custom methods on it to extend its functionality as needed.
type dispatchDao struct {
	*internal.DispatchDao
}

var (
	// Dispatch is a globally accessible object for table ct_dispatch operations.
	Dispatch = dispatchDao{internal.NewDispatchDao()}
)

// Add your custom methods and functionality below.
