// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/collect/dao/internal"
)

// stepsDao is the data access object for the table ct_steps.
// You can define custom methods on it to extend its functionality as needed.
type stepsDao struct {
	*internal.StepsDao
}

var (
	// Steps is a globally accessible object for table ct_steps operations.
	Steps = stepsDao{internal.NewStepsDao()}
)

// Add your custom methods and functionality below.
