// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/collect/dao/internal"
)

// templateDao is the data access object for the table ct_template.
// You can define custom methods on it to extend its functionality as needed.
type templateDao struct {
	*internal.TemplateDao
}

var (
	// Template is a globally accessible object for table ct_template operations.
	Template = templateDao{internal.NewTemplateDao()}
)

// Add your custom methods and functionality below.
